# Generated by Django 3.1.4 on 2021-02-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siparis',
            old_name='ürünadi',
            new_name='urunadi',
        ),
    ]
